version: '3.7'
services:

  # ---------------------------------------------------------------------------- #
  #                                     NGINX                                    #
  # ---------------------------------------------------------------------------- #

  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: nginx-certbot
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./configs:/etc/nginx/user_conf.d:ro
      - /srv/nginx/nginx_secrets:/etc/letsencrypt
      - /srv/nginx/logs/:/logs/
    networks:
      - nginx

networks:
  nginx:
    driver: bridge